app:
  public-host: ${PUBLIC_HOST}

spring:
  config:
    import: classpath:additional-application.properties
  datasource:
    url: jdbc:postgresql://localhost:29092/planner?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  token:
    secret: 'P2a3KPYdZruEaxt9hpcf4HmwzwerfvatHcZSksnsakIUHvsFAsdVSS'
