app:
  rabbit:
    queue: EMAIL_SENDING_TASKS
    exchange: email
    routing_key: email
  token-confirm:
    lifetime: 24h

springdoc:
  show-actuator: true
  enable-native-support: true
  swagger-ui:
    tagsSorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true

#logging:
#  level:
#    root: DEBUG

server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres
    password: 9889
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: validate

flyway:
  enabled: true

  rabbitmq:
    username: admin


jwt:
  token:
    lifetime: 24h
    secret: 'P2a3KPYdZruEaxt9hpcf4HmwzwerfvatHcZSksnsakIUHvsFAsdVSS'
