app:
  public-host: ${PUBLIC_HOST}

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://postgres:5432/planner?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  token:
    secret: ${JWT_SECRET}