server:
  port: 8080

app:
#  rabbit:
#    queue: EMAIL_SENDING_TASKS
#    exchange: email
#    routing_key: email
  token-confirm:
    lifetime: 24h

jwt:
  token:
    lifetime: 24h
    secret: 'P2a3KPYdZruEaxt9hpcf4HmwzwerfvatHcZSksnsakIUHvsFAsdVSS'

spring:
#  config:
#    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres
    password: 8998
  jpa:
    show-sql: true
  hibernate:
    ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:29092

flyway:
  enabled: true

#  rabbitmq:
#    username: admin