--CREATE TABLE IF NOT EXISTS confirm_tokens
--(
--    id      SERIAL PRIMARY KEY NOT NULL,
--    token         uuid            NOT NULL UNIQUE,
--    person_id     BIGINT          NOT NULL,
--    expired       TIMESTAMP       NOT NULL,
--    CONSTRAINT fk_person_id FOREIGN KEY (person_id) REFERENCES person (id)
--);